In [260]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression as LR

In [328]:
data = pd.read_csv("./ds1_test.csv")

In [363]:
x, y = np.c_[np.ones((800,1)), data[['x_1', 'x_2']]], np.array(data['y']).reshape(800,1)


class LogisticRegression:
    """Logistic regression with Newton's Method as the solver.

    Example usage:
        > clf = LogisticRegression()
        > clf.fit(x_train, y_train)
        > clf.predict(x_eval)
    """
    def __init__(self, step_size=0.01, max_iter=1000000, eps=1e-5,
                 theta_0=None, verbose=True):
        """
        Args:
            step_size: Step size for iterative solvers only.
            max_iter: Maximum number of iterations for the solver.
            eps: Threshold for determining convergence.
            theta_0: Initial guess for theta. If None, use the zero vector.
            verbose: Print loss values during training.
        """
        self.theta = theta_0
        self.step_size = step_size
        self.max_iter = max_iter
        self.eps = eps
        self.verbose = verbose
        self.m = 0  # num of training examples
        self.n = 0 # num of features

    def sigmoid(self, theta, x):
        #hypothesis function
        h = []
        for xi in x:
            xi = xi.reshape(1,3)
            v = 1 / (1 + np.exp(-xi.dot(theta)))
            h.append(v)
        return np.array(h).reshape(-1, 1)

    def j_prime(self, theta, x, y):
        return (-1/self.m)*x.T.dot(y - self.sigmoid(theta, x))
    

    def j_hess(self, theta, x, y):
        g = self.sigmoid(theta, x)
        s = np.diag(np.diag(g.dot((1-g).T)))
        return (1/self.m)*x.T.dot(s).dot(x)

    def fit(self, x, y):
        """Run newton's method to minimize j(theta) for logistic regression."""
        self.m = len(x)
        self.n = len(x[0])
        self.theta = np.zeros((self.n,1))
#         print(self.sigmoid(self.theta, x))
        print(self.j_prime(self.theta, x, y))
#         print(np.linalg.inv(self.j_hess(self.theta, x, y)).dot(self.j_prime(self.theta, x, y)))
        count = 0
        theta = np.linalg.inv(self.j_hess(self.theta, x, y)).dot(self.j_prime(self.theta, x, y))
        while abs(theta - self.theta).all() > self.eps and count < self.max_iter:
            self.theta = theta
            hessinv = np.linalg.inv(self.j_hess(theta, x, y)).reshape(self.n, self.n)
            print(hessinv)
            theta = theta - hessinv.dot(self.j_prime(theta, x, y))
            count += 1
                
        print(self.theta)

In [364]:
clf = LogisticRegression()
clf.fit(x, y)


[[-0.        ]
 [-0.39548487]
 [-2.5214322 ]]
[[13.54645873 -6.58288573 -0.01400028]
 [-6.58288573  8.12865678 -0.60350622]
 [-0.01400028 -0.60350622  0.13040407]]
[[ 53.32729473 -29.8210194   -1.48135188]
 [-29.8210194   31.7900795   -2.28742784]
 [ -1.48135188  -2.28742784   1.00292524]]
[[17.89086609 -4.4462476  -1.79387412]
 [-4.4462476  11.32316497 -2.00701235]
 [-1.79387412 -2.00701235  1.03508051]]
[[24.88312885 -8.51259629 -2.05829504]
 [-8.51259629 14.95347225 -2.17398646]
 [-2.05829504 -2.17398646  1.16906151]]
[[27.30511356 -9.88487584 -2.16654554]
 [-9.88487584 16.14764084 -2.22188999]
 [-2.16654554 -2.22188999  1.21596112]]
[[27.45478414 -9.96777446 -2.17404299]
 [-9.96777446 16.21992894 -2.22488052]
 [-2.17404299 -2.22488052  1.21910989]]
[[27.45525912 -9.96803223 -2.17406901]
 [-9.96803223 16.22015643 -2.22489074]
 [-2.17406901 -2.22489074  1.21912083]]
[[27.45525912 -9.96803223 -2.17406901]
 [-9.96803223 16.22015643 -2.22489074]
 [-2.17406901 -2.22489074  1.21912083]]
[

In [365]:
 def sigm(theta, x):
        #hypothesis function
    h = []
    for xi in x:
        xi = xi.reshape(1,3)
        v = 1 / (1 + np.exp(-xi.dot(theta)))
        h.append(v)
    return np.array(h).reshape(-1, 1)

yt = sigm(clf.theta, x)

for i in range(len(yt)):
    if yt[i] <= 0.5:
        yt[i] = 0
    else:
        yt[i] = 1



In [366]:
c = 0
for i in range(len(y)):
    if yt[i] != y[i]:
        c +=1
        print(yt[i], y[i])
        
        
c

[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[1.] [0.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]
[0.] [1.]


161